### PR TITLE
Update text on homepage and in volunteer info footer.

### LINKED ISSUE #4: Confusing text about active responses
## Issue Overview

This text is confusing right now since there's only one: 'Click on any active response below to be taken to that response site.'

Also, I'm not sure it needs explanation if things look clickable. That might mean changing the style a bit and having things behave more normally. For example, just the link would be clickable.

### LINKED ISSUE #5: Change help provided wording
## Issue Overview

This line:

Our response sites provide information emergency response resources available to people affected by the disaster, including:
* shelters in the affected area
* distribution points for water and food

Might work more simply as:

Each site can tell you about ways to get help in a disaster emergency, like a hurricane or flood. They can tell you things like:
* Where shelters are
* Where to get food and water

Also, make sure that this site can tell you other things or otherwise it could be confusing.

### LINKED ISSUE #6: Adjust volunteering blurb
## Issue Overview

If there's not a reason to include the volunteering link in both places that talk about volunteering, I think it'd be great to have them in both places. Also, I think a little simplifying of wording could help. This:

'If you’d like to help out with this effort, information on volunteering is at the bottom of this page.'

Might work better as:

'If you want to help out, you can find out more [here].'

### LINKED ISSUE #8: Volunteering links don't lead to a useful site
## Issue Overview

The volunteering links just lead to CfA's main page. If I were trying to volunteer to help, I would be confused. If there's nothing to link to yet, I'd suggest commenting out that text for now. One possible place to link to temporarily might be the google doc.

### PR DESCRIPTION
**Pull request by nihonjinrxs**
## Description

Closes #4 Closes #5 Closes #6 Closes #8

This PR changes text to make language plainer, per the referenced issues.

## List of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Text changes (content changes that do not impact functionality)

## Checklist:
- [x] This pull request relates to a ticket.
- [x] This code is tested.
- [ ] I want my code added to the response theme.

### CODE REVIEW

**Comment by nihonjinrxs** [comment]
@GovInTrenches @plocket review appreciated. Note that for the homepage content, there are 3 states for the text: (1) no active responses (2) 1 active response (3) more than one active response.

**Comment by plocket** [comment]
As soon as I get a chance too look up pulling a PR from someone else's repo, I'll be on this!

**Comment by nihonjinrxs** [comment]
This is a minor change and has been well tested. I'm going to merge, and we can change again if needed.

**Comment by plocket** [comment]
This says it closes #8, but the volunteering link just leads back to https://www.hurricane-response.org/about/, where the link leads to https://www.hurricane-response.org/about/. If that's the useful page, then the link in the footer shouldn't be there on this page.

**Pull request merged**
